### ISSUE TITLE
NumEnter

### ISSUE THREAD

**Issue by TheCodyCZ** [StarlitEvelyn/Concordia-Client#11]
NumEnter is Entering instead of sending.

**Comment by StarlitEvelyn** [comment]
Should be fixed, just need to test it <3

**Comment by StarlitEvelyn** [comment]
Fixed by commit https://github.com/StarlitEvelyn/Concordia-Client/commit/f3f41d3a6ee807033d55c78ea7673cf1d2757a3b, final version in commit https://github.com/StarlitEvelyn/Concordia-Client/commit/a0eaf067472905daef4c7aacf2f4eaf7b5aee612

Thank you for the issue <3
